#!/usr/bin/perl
#
# ssu-build
# Eric Nawrocki
# EPN, Wed Oct 14 06:57:00 2009
#
# Usage: ssu-build <alignment file to build CM from>
#             
# Synopsis:
# Builds a CM from an input stockholm alignment using cmbuild parameters 
# that are recommended for building SSU CMs.
#
# See definition of $options_usage for options, below.
#
use Getopt::Long;
use Cwd 'abs_path';
use strict;

my $total_time = -1 * time();
my $usage =  "Usage: ssu-build [options] <Stockholm alignment file to build CM from>\n";
my $options_usage  = "where general options are:\n";
#                           1         2         3         4         5         6         7         8
#                  12345678901234567890123456789012345678901234567890123456789012345678901234567890
$options_usage .= "  -h            : show brief help on version and usage\n";
$options_usage .= "  -o <s>        : name the CM *file* <s> (by default, the '.stk' suffix becomes '.cm')\n";
#$options_usage .= "  -n <s>        : name the CM model itself <s>\n";
$options_usage .= "  -F            : force; allow overwriting of CM file\n" ,
$options_usage .= "  --append <s>  : append this model to CM file <s>\n";
$options_usage .= "  --key-out <s> : add <s> to all output file names, before the suffix\n";
$options_usage .= "\noptions for building a model of only a contiguous subset of alignment columns:\n";
$options_usage .= "  --start-rf <n>  : build a model that starts at *consensus* position <s>\n";
$options_usage .= "  --end-rf <n>    : with --start-rf, set model end *consensus* position as <n>\n";
$options_usage .= "  --start-all <n> : build a model that starts at *alignment* position <s>\n";
$options_usage .= "  --end-all <n>   : with --start-all, set model end *alignment* position as <n>\n";
$options_usage .= "  -1              : output alignment(s) in non-interleaved, 1 line/seq format\n";
$options_usage .= "  --ps2pdf        : convert mask postscript drawings to pdfs using ps2pdf\n";
$options_usage .= "  --ps-keep       : with --ps2pdf, keep both postcript files and pdf files\n";
$options_usage .= "\noptions for defining consensus and numbering alignment columns (no model will be built):\n";
$options_usage .= "  --num-rf <n>  : define and number the consensus columns and exit\n";
$options_usage .= "  --num-all <n> : number all columns in the alignment and exit\n";
$options_usage .= "\nexpert options for model construction:\n";
$options_usage .= "  --gapthresh <x> : set fraction of gaps to allow in a consensus column to <x> (default: 0.8)\n";
$options_usage .= "  --rf            : use consensus column (#=GC RF) annotation in alignment\n";
$options_usage .= "  --eent          : use 'entropy weighting' method to achieve relative entropy target\n";
$options_usage .= "  --ere <x>       : with --eent, set target relative entropy as <x>\n";

###################
# Process options #
###################
my %opt_H = ();
$opt_H{"-h"}          = 0;
$opt_H{"-o"}          = "";
$opt_H{"-F"}          = 0;
$opt_H{"--append"}    = "";
$opt_H{"--key-out"}   = "";
$opt_H{"--start-rf"}  = "";
$opt_H{"--end-rf"}    = "";
$opt_H{"--start-all"} = "";
$opt_H{"--end-all"}   = "";
$opt_H{"-1"}          = 0;
$opt_H{"--ps2pdf"}    = 0;
$opt_H{"--ps-keep"}   = 0;
$opt_H{"--num-rf"}    = 0;
$opt_H{"--num-all"}   = 0;
$opt_H{"--gapthresh"} = "";
$opt_H{"--rf"}        = 0;
$opt_H{"--eent"}      = 0;
$opt_H{"--ere"}       = "";

my $df_gapthresh = 0.80;

Getopt::Long::Configure ("bundling");
my $opt_return = GetOptions
    ('h'           => \$opt_H{"-h"}, 
     'o=s'         => \$opt_H{"-o"},
     'F'           => \$opt_H{"-F"},
     'append=s'    => \$opt_H{"--append"},
     'key-out=s'   => \$opt_H{"--key-out"},
     'start-rf=i'  => \$opt_H{"--start-rf"},
     'end-rf=i'    => \$opt_H{"--end-rf"},
     'start-all=i' => \$opt_H{"--start-all"},
     'end-all=i'   => \$opt_H{"--end-all"},
     '1'           => \$opt_H{"-1"},
     'ps2pdf'      => \$opt_H{"--ps2pdf"},
     'ps-keep'     => \$opt_H{"--ps-keep"},
     'num-rf'      => \$opt_H{"--num-rf"},
     'num-all'     => \$opt_H{"--num-all"},
     'gapthresh=f' => \$opt_H{"--gapthresh"},
     'rf'          => \$opt_H{"--rf"},
     'eent'        => \$opt_H{"--eent"},
     'ere=f'       => \$opt_H{"--ere"});
 
if($opt_return != 1) { exit(1); }

if ($opt_H{"-h"}) { print $usage . "\n"; print $options_usage; exit(1); } 

my $key_out;
if($opt_H{"--key-out"}  ne "") { $key_out   = "." . opt_H{"--key-out"};  }

##############################################################################
# Determine the "mode" to run and check for incompatible option combinations.#
##############################################################################
# There are only 2 possible modes, they are exclusive.
my $do_build_mode  = 1; # default mode, build a CM
my $do_number_mode = 0; # number alignment columns and exit
if(($opt_H{"--num-rf"}) || ($opt_H{"--num-all"})) {
    $do_build_mode  = 0;
    $do_number_mode = 1;
}
# In build mode, we may also optionally truncate the alignment
my $do_truncate = 0;
if($opt_HR->{"--start-rf"}  ne "") { $do_truncate = 1; }
if($opt_HR->{"--start-all"} ne "") { $do_truncate = 1; }

if(($opt_H{"--num-all"}) || ($opt_H{"--num-rf"})) { 
    # --num-all and --num-rf are  incompatible with all other options except --rf, --key-out, -1
    if(($opt_H{"-o"}          ne "") || 
       ($opt_H{"-F"})                ||
       ($opt_H{"--append"})          ||
       ($opt_H{"--start-rf"}  ne "") || 
       ($opt_H{"--end-rf"}    ne "") ||
       ($opt_H{"--start-all"} ne "") || 
       ($opt_H{"--end-all"}   ne "") ||
       ($opt_H{"--ps2pdf"})          ||
       ($opt_H{"--ps-keep"})         ||
       ($opt_H{"--eent"})            ||
       ($opt_H{"--ere"}       ne "")) {
	printf STDERR ("\nERROR, --num-rf and --num-all are incompatible with all other options except for --rf, -1, and --key-out.\n"); exit(1);
    }
}
if(($opt_H{"--start-rf"} ne "") && ($opt_H{"--end-rf"} eq "")) { 
    printf STDERR ("\nERROR, if --start-rf is enabled, --end-rf must also be enabled.\n"); exit(1); 
}
if(($opt_H{"--start-rf"} eq "") && ($opt_H{"--end-rf"} ne "")) { 
    printf STDERR ("\nERROR, if --end-rf is enabled, --start-rf must also be enabled.\n"); exit(1); 
}
if(($opt_H{"--start-all"} ne "") && ($opt_H{"--end-all"} eq "")) { 
    printf STDERR ("\nERROR, if --start-all is enabled, --end-all must also be enabled.\n"); exit(1); 
}
if(($opt_H{"--start-all"} eq "") && ($opt_H{"--end-all"} ne "")) { 
    printf STDERR ("\nERROR, if --end-all is enabled, --start-all must also be enabled.\n"); exit(1); 
}
if(($opt_H{"--ere"} ne "") && (! ($opt_H{"--eent"}))) { 
    printf STDERR ("\nERROR, if --ere is enabled, --eent must also be enabled.\n"); exit(1); 
}
if(($opt_H{"--append"} ne "") && (($opt_H{"-o"}) ne "")) { 
    printf STDERR ("\nERROR, --append is incompatible with -o.\n"); exit(1); 
}

################
# Print banner #
################
my @log2printA = ();
print_banner($0, \%opt_H, \@ARGV, \@log2printA);

if(scalar(@ARGV) != 1) {   
    print "Incorrect number of command line arguments.\n";
    print $usage;
    print "\nTo see more help on available options, do ssu-draw -h\n\n";
    exit(1);
}
my ($aln_file) = $ARGV[0];

##################################
# Validate that everything is go #
##################################
my ($cmbuild, $cm_file, $alimanip, $ssdraw, $template_file, $num_aln_file, $log_file);
validate_setup($aln_file, $key_out, \%opt_H, $do_build_mode, $do_number_mode, $do_truncate,
	       \$cmbuild, \$cm_file, \$alimanip, \$ssdraw, \$template_file, \$log_file);

if(scalar(@ARGV) != 1) {   
    print "Incorrect number of command line arguments.\n";
    print $usage;
    print "\nTo see more help on available options, do ssu-mask -h\n\n";
    exit(1);
}

#####################
# Handle Build mode #
#####################
my $ssdraw_failed_at_least_once = 0;
my $ssdraw_worked_at_least_once = 0;
my $gapthresh = $opt_H{"--gapthresh"};
if($gapthresh eq "")  { $gapthresh = $df_gapthresh; }

if($do_build_mode) 
{ 
    if($do_truncate) { 
	run_alimanip_to_truncate($alimanip, $aln_file, $num_aln_file, $gapthresh, \%opt_H, \@log2printA);
	
    run_cmbuild($cmbuild, $aln_file, $cm_file, $gapthresh, \%opt_H, \@log2printA);
}    

######################
# Handle Number mode #
######################
if($do_number_mode) 
{ 
    run_alimanip_to_number($alimanip, $aln_file, $gapthresh, \%opt_H, \@log2printA);
}

push(@log2printA, sprintf("#\n"));
printf($log2printA[(scalar(@log2printA)-1)]);
push(@log2printA, sprintf("# This output saved to log file: $log_file.\n"));
printf($log2printA[(scalar(@log2printA)-1)]);
print_log($log_file, \@log2printA);

exit(0);


###############
# subroutines #
###############

#####################################################################
# Subroutine: print_banner()
# Incept:     EPN, Wed Oct 14 13:53:05 2009
# 
# Purpose:    Print the ssu-build banner.
#
# Arguments: 
#    $script_call:     call used to invoke this (ssu-build) script
#    $opt_HR:          REFERENCE to hash of command-line options
#    $argv_ref:        reference to @ARGV, command-line arguments
#    $log2printAR:     reference to log2print array with flog file text
#
# Returns:    Nothing, if it returns, everything is valid.
# 
####################################################################
sub print_banner { 
    my $narg_expected = 4;
    if(scalar(@_) != $narg_expected) { printf STDERR ("ERROR, print_banner() entered with %d != %d input arguments.\n", scalar(@_), $narg_expected); exit(1); } 
    my ($script_call, $opt_HR, $argv_ref, $log2printAR) = @_;
    my ($i, $script_name, $start_log_line);

    my $enabled_options;
    if($opt_HR->{"-h"})                { $enabled_options .= " -h"; }
    if($opt_HR->{"-o"}          ne "") { $enabled_options .= " -o " .          $opt_HR->{"-o"}; }
    if($opt_HR->{"-F"})                { $enabled_options .= " -F"; }
    if($opt_HR->{"--append"})          { $enabled_options .= " --append"; }
    if($opt_HR->{"--key-out"}   ne "") { $enabled_options .= " --key-out " .   $opt_HR->{"--key-out"}; }   
    if($opt_HR->{"--start-rf"}  ne "") { $enabled_options .= " --start-rf " .  $opt_HR->{"--start-rf"}; }  
    if($opt_HR->{"--end-rf"}    ne "") { $enabled_options .= " --end-rf " .    $opt_HR->{"--end-rf"}; }   
    if($opt_HR->{"--start-all"} ne "") { $enabled_options .= " --start-all " . $opt_HR->{"--start-all"}; }  
    if($opt_HR->{"--end-all"}   ne "") { $enabled_options .= " --end-all " .   $opt_HR->{"--end-all"}; }  
    if($opt_HR->{"--num-rf"})          { $enabled_options .= " --num-rf"; }  
    if($opt_HR->{"--num-all"})         { $enabled_options .= " --num-all"; }
    if($opt_HR->{"--gapthresh"} ne "") { $enabled_options .= " --gapthresh " . $opt_HR->{"--gapthresh"}; } 
    if($opt_HR->{"--rf"})              { $enabled_options .= " --rf"; }  
    if($opt_HR->{"--eent"})            { $enabled_options .= " --eent"; }
   if($opt_HR->{"--ere"}        ne "") { $enabled_options .= " --ere " .       $opt_HR->{"--ere"}; }

    $script_call =~ s/^\.+\///;
    $script_name = $script_call;
    $script_name =~ s/.+\///;

    $start_log_line = scalar(@{$log2printAR});

    push(@{$log2printAR}, sprintf("\# $script_name :: build SSU rRNA covariance models\n"));
    push(@{$log2printAR}, sprintf("\# SSU-ALIGN 0.1 (October 2009)\n"));
    push(@{$log2printAR}, sprintf("\# Copyright (C) 2009 HHMI Janelia Farm Research Campus\n"));
    push(@{$log2printAR}, sprintf("\# Freely distributed under the GNU General Public License (GPLv3)\n"));
    push(@{$log2printAR}, sprintf("\# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -\n"));
    push(@{$log2printAR}, sprintf("%-10s %s ", "# command:", $script_call . $enabled_options));
    for($i = 0; $i < scalar(@{$argv_ref}) - 1; $i++) { 
	push(@{$log2printAR}, sprintf("$argv_ref->[$i] "));
    }
    push(@{$log2printAR}, sprintf("$argv_ref->[$i]\n"));
    push(@{$log2printAR}, sprintf("%-10s ", "# date:"));
    push(@{$log2printAR}, sprintf(scalar localtime()));
    push(@{$log2printAR}, sprintf("\n"));

    for($i = $start_log_line; $i < scalar(@{$log2printAR}); $i++) { 
	printf($log2printAR->[$i]);
    }
    return;
}


#####################################################################
# Subroutine: validate_setup()
# Incept:     EPN, Mon Nov  3 15:05:56 2008
# 
# Purpose:    Validate that: 
#             - the alignment file exists and ends in '.stk' or '.sto'
#             - the required executable programs exist.
#             - the CM file we're building does not exist (unless -F or -A)
#             - determine name for output '.log' file
#             - determine name for numbered alignment file (we may or may not need this)
#             - determine name for truncated alignment file (we may or may not need this)
#
# Arguments: 
# $aln_file:           the alignment file we'll build CM from (or number columns for)
# $key_out:            string to append to names of output files
# $opt_HR:             reference to the hash of command-line options
# $do_build_mode:      TRUE if we're in build mode (will build a CM)
# $do_number_mode:     TRUE if we're in number mode, we'll not build a CM
# $do_truncate:        TRUE if we will truncate the alignment
# $cmbuild_ref:        RETURN; the cmbuild command
# $cm_file_ref:        RETURN; the path to the CM file we'll write to
# $alimanip_ref:       RETURN; the esl-alimanip command (only nec if building truncated model)
# $ssdraw_ref:         RETURN; the esl-ssdraw command (only nec if building truncated model)
# $template_file_ref:  RETURN; the path to the template file for ssdraw (only nec if building truncated model)
# $log_file_ref:       RETURN; the path and name of what will become the log output file
#
# Returns:    Nothing, if it returns, everything is valid.
# 
# Exits:      If any of the above validations do not occur, we
#             print a message to STDERR explaining why it's
#             exiting early and then exit with non-zero status.
#
####################################################################
sub validate_setup { 
    my $narg_expected = 12;
    if(scalar(@_) != $narg_expected) { printf STDERR ("\nERROR, validate_setup() entered with %d != %d input arguments.\n", scalar(@_), $narg_expected); exit(1); } 
    my($aln_file, $key_out, $opt_HR, $do_build_mode, $do_number_mode, $do_truncate, $cmbuild_ref, $cm_file_ref, $alimanip_ref, $ssdraw_ref, $template_file_ref, $log_file_ref) = @_;

    #Validate that the alignment file exists.
    if(!(-e $aln_file)) { printf STDERR ("\nERROR, alignment file $aln_file does not exist.\n"); exit(1); }
    my $root = $aln_file; 
    $root =~ s/.+\///;  #remove directory path
    if($root =~ s/\.stk$//)    { ; }
    elsif($root =~ s/\.sto$//) { ; }
    # otherwise we'll just append '.cm' to the full name of the alignment file

    my $log_file = $root . $key_out . ".ssu-build.log";

    my $cm_file = "";
    my $cmbuild = "";
    my $trash = "";
    my $alimanip = "";
    if($do_build_mode) { 
	if($opt_HR->{"--append"} ne "") { 
	    $cm_file = $opt_HR->{"--append"};
	    if(!(-e $cm_file)) { 
		printf STDERR ("\nERROR, --append $cm_file enabled, but $cm_file does not exist.\n"); exit(1); 
	    }
	}
	else { 
	    if($opt_HR->{"-o"} ne "") { # we've already checked that user did not enable both -o and --append (before printing banner in main)
		$cm_file = $opt_HR->{"-o"};
	    }
	    else { 
		$cm_file = $root . ".cm";
	    }
	    if(-e $cm_file) { 
		if(!($opt_HR->{"-F"})) { 
		    printf STDERR ("ERROR, CM file $cm_file already exists. Delete it or use -F to overwrite it.\n"); exit(1); 
		}
	    }
	}

	#Validate that ssu-cmbuild exists and is in path
	$cmbuild = "ssu-cmbuild";
	$trash = `$cmbuild -h`;
	if($? == -1) { printf STDERR ("\nERROR, the required executable $cmbuild is not in your PATH environment\nvariable. See the User's Guide Installation section.\n"); exit(1); } 
    }

    my $alimanip = "";
    my $ssdraw_file = "";
    my $template_file = "";

    if($do_truncate || $do_number_mode) { 
	# verify that we can run esl-alimanip
	$alimanip = "ssu-esl-alimanip";
	$trash = `$alimanip -h`;
	if($? == -1) { printf STDERR ("\nERROR, the required executable $alimanip is not in your PATH environment\nvariable. See the User's Guide Installation section.\n"); exit(1); } 
    }
    if($do_truncate) { 
	#verify that we know where the template file and esl-ssdraw are 
	my $ssualigndir = $ENV{'SSUALIGNDIR'};
	if(! exists($ENV{'SSUALIGNDIR'})) { 
	    printf STDERR ("\nERROR, the SSUALIGNDIR environment variable should be set but it's not.\nFor help, see the User's Guide Installation section.\n"); exit(1);
	    exit(1); 
	}
	$template_file = $ssualigndir . "/ssu-align-0p1.ps";
	if(!(-e $template_file)) { $template_file = ""; }

	my $ssdraw = "";
	if($template_file ne "") { 
	    $ssdraw = "ssu-esl-ssdraw";
	    $trash = `$ssdraw -h`;
	    if($? == -1) { $ssdraw = ""; }
	}
    }	
    #Validate that 'ps2pdf' exists if --ps2pdf.
    if($opt_HR->{"--ps2pdf"}) { 
	#If --ps2pdf, validate that ps2pdf is in PATH
	$trash = `ps2pdf 2>&1`;
	if($? == -1) { printf STDERR ("\nERROR, --ps2pdf was enabled, but ps2pdf is not in your PATH environment variable.\n"); }
    }

    $$cmbuild_ref       = $cmbuild;
    $$cm_file_ref       = $cm_file;
    $$alimanip_ref      = $alimanip;
    $$ssdraw_ref        = $ssdraw;
    $$template_file_ref = $template_file;
    $$num_aln_file_ref  = $num_aln_file;
    $$log_file_ref      = $log_file;
    
    return;
}

#####################################################################
# Subroutine: print_timing()
# Incept:     EPN, Tue Jun 16 08:52:08 2009
# 
# Purpose:    Print a timing in hhhh:mm:ss format to 1 second precision.
#
# Arguments: 
#   $prefix:      string that will precede timing output
#   $inseconds:   number of seconds the script required
#   $log2printAR: reference to log2print array with log file text
#
# Returns:    Nothing, if it returns, everything is valid.
# 
####################################################################
sub print_timing { 
    my $narg_expected = 3;
    if(scalar(@_) != $narg_expected) { printf STDERR ("\nERROR, print_timing() entered with %d != %d input arguments.\n", scalar(@_), $narg_expected); exit(1); } 
    my ($prefix, $inseconds, $log2printAR) = @_;
    my ($hours, $minutes, $seconds, $thours, $tminutes, $tseconds, $start_log_line);

    $start_log_line = scalar(@{$log2printAR});

    $hours = int($inseconds / 3600);
    $inseconds -= ($hours * 3600);
    $minutes = int($inseconds / 60);
    $inseconds -= ($minutes * 60);
    $seconds = $inseconds;
    $thours   = $hours;
    $tminutes = $minutes;
    $tseconds = $seconds;

    if($hours < 10)   { $thours   = "0" . $thours; }
    if($minutes< 10)  { $tminutes = "0" . $tminutes; }
    if($seconds< 10)  { $tseconds = "0" . $tseconds; }

    push(@{$log2printAR}, sprintf("%s %2s:%2s:%2s\n", $prefix, $thours, $tminutes, $tseconds));

    my $i;
    for($i = $start_log_line; $i < scalar(@{$log2printAR}); $i++) { 
	printf($log2printAR->[$i]);
    }
}

#####################################################################
# Subroutine: print_log()
# Incept:     EPN, Tue Jun 16 09:23:55 2009
# 
# Purpose:    Print the log.
#
# Arguments:
#   $log_file:    file to print log to.
#   $log2printAR: reference to array, each element is line of text in log.
#
# Returns:    Nothing, if it returns, everything is valid.
# 
####################################################################
sub print_log { 
    my $narg_expected = 2;
    if(scalar(@_) != $narg_expected) { printf STDERR ("ERROR, print_log() entered with %d != %d input arguments.\n", scalar(@_), $narg_expected); exit(1); } 
    my ($log_file, $log2printAR) = @_;
    my ($start_log_line, $line);

    if(open(LOG,  ">" . $log_file) == 0) { printf STDERR ("ERROR, could not open $log_file for writing.\n"); exit(1); }
    foreach $line (@{$log2printAR}) { print LOG $line; }
    close(LOG);

    return;
}


#####################################################################
# subroutine: run_cmbuild()
# incept:     EPN, Wed Oct 14 14:29:00 2009
# 
# Purpose:    Run cmbuild on an alignment file to create CM(s).
#
# Arguments:  
#   $cmbuild:          path and name of cmbuild/ssu-cmbuild executable
#   $aln_file:         path and name of alignment file to build CM from
#   $cm_file:          path and name of CM file to create/write to
#   $gapthresh:        gap threshold to use when building the model
#   $opt_HR:           reference to the hash of command-line options
#   $log2printAR:      reference to log2print array with log file text
# 
# Returns:  Nothing, if it returns, everything is valid.
# 
####################################################################
sub run_cmbuild {
    my $narg_expected = 6;
    if(scalar(@_) != $narg_expected) { printf STDERR ("ERROR, run_cmbuild() entered with %d != %d input arguments.\n", scalar(@_), $narg_expected); exit(1); } 
    my ($cmbuild, $aln_file, $cm_file, $gapthresh, $opt_HR, $log2printAR) = @_;

    my $extra_opts = "";

    if($opt_HR->{"--append"} ne "") { $extra_opts .= " -A "; }
    if($opt_HR->{"--rf"})           { $extra_opts .= " --rf " . $opt_HR->{"--rf"}; }
    if($opt_HR->{"-F"})             { $extra_opts .= " -F"; }

    if($opt_HR->{"--eent"})  { $extra_opts .= " --eent"; }
    else                  { $extra_opts .= " --enone"; }
    if($opt_HR->{"--ere"})   { $extra_opts .= " --ere " . $opt_HR->{"--ere"}; }
    
    push(@{$log2printAR}, sprintf("#\n# Building CM(s)...\n"));
    printf($log2printAR->[(scalar(@{$log2printAR})-1)]);
    push(@{$log2printAR}, sprintf("#\n"));
    printf($log2printAR->[(scalar(@{$log2printAR})-1)]);
    
    my $command = "$cmbuild $extra_opts --gapthresh $gapthresh $cm_file $aln_file 2>&1";
    my $tmp = `$command`;
    if(($? >> 8) != 0) { 
	printf STDERR ("\nERROR, the command \(\"$command\"\) unexpectedly returned non-zero exit status %d\nand output:\n$tmp\n", ($? >> 8)); exit($? >> 8); 
    }
    
    my @tmpA = split("\n", $tmp);
    my ($i, $line);
    my $ncm       = 0;
    my @cm_nameA  = ();
    my @nseqA     = ();
    my @eff_nseqA = ();
    my @alenA     = ();
    my @clenA     = ();
    my @bpsA      = ();
    my @bifA      = ();
    my @cm_reA    = ();
    my @hmm_reA   = ();
    my $max_width_name = length("CM name"); 
    my $max_width_file = length($cm_file);
    if($max_width_file < length("CM file name")) { $max_width_file = length("CM file name"); }
    foreach $line (@tmpA) { 
	  ######################################################################################
	  # Example cmbuild output:
	  #
          #  aln  cm idx  name         nseq  eff_nseq    alen   clen   bps  bifs     CM    HMM
          # ----  ------  -------  --------  --------  ------  -----  ----  ----  -----  -----
          #    1       1  archaea        23     23.00    1563   1508   471    30  1.434  1.235
	  ######################################################################################
	if($line =~ /^\s*\d+\s+\d+\s+(\S+)\s+(\d+)\s+(\S+)\s+(\d+)\s+(\d+)\s+(\d+)\s+(\d+)\s+(\S+)\s+(\S+)/) { 
	    push(@cm_nameA,  $1);
	    push(@nseqA,     $2); 
	    push(@eff_nseqA, $3); #not printed
	    push(@alenA,     $4); 
	    push(@clenA,     $5);
	    push(@bpsA,      $6); 
	    push(@bifA,      $7); #not printed
	    push(@cm_reA,    $8); #not printed
	    push(@hmm_reA,   $9); #not printed
	    if(length($1) > $max_width_name) { $max_width_name = length($1); }
	    $ncm++;
	}
    }

    my $dashes_file = ""; for($i = 0; $i < $max_width_file; $i++) { $dashes_file .= "-"; }
    my $dashes_name = ""; for($i = 0; $i < $max_width_name; $i++) { $dashes_name .= "-"; }
    if($ncm > 0) { 
	push(@{$log2printAR}, sprintf("# %-*s  %-*s  %6s  %9s  %9s  %4s\n", $max_width_file, "", $max_width_name, "", "num", "alignment", "consensus", "num"));
	printf($log2printAR->[(scalar(@{$log2printAR})-1)]);
	push(@{$log2printAR}, sprintf("# %-*s  %-*s  %6s  %9s  %9s  %4s\n", $max_width_file, "CM file name", $max_width_name, "CM name", "seqs", "length", "length", "bps"));
	printf($log2printAR->[(scalar(@{$log2printAR})-1)]);
	push(@{$log2printAR}, sprintf("# %-*s  %-*s  %6s  %9s  %9s  %4s\n", $max_width_file, $dashes_file, $max_width_name, $dashes_name, "------", "---------", "---------", "----"));
	printf($log2printAR->[(scalar(@{$log2printAR})-1)]);

	for($i = 0; $i < $ncm; $i++) { 
	    push(@{$log2printAR}, sprintf("  %-*s  %-*s  %6s  %9s  %9s  %4s\n", $max_width_file, $cm_file, $max_width_name, $cm_nameA[$i], $nseqA[$i], $alenA[$i], $clenA[$i], $bpsA[$i]));
	    printf($log2printAR->[(scalar(@{$log2printAR})-1)]);
	}
    }
    return;
}


#####################################################################
# subroutine: run_alimanip_to_number()
# incept:     EPN, Fri Oct 16 14:08:22 2009
# 
# Purpose:    Run esl-alimanip/ssu-esl-alimanip on an alignment file 
#             to number the columns within it. This is only called if
#             either --num-rf or --num-all (or both) are enabled.
#
# Arguments:  
#   $alimanip:         path and name of esl-alimanip/ssu-esl-alimanip executable
#   $aln_file:         path and name of alignment file to build CM from
#   $gapthresh:        gap threshold to use when building the model
#   $opt_HR:           reference to the hash of command-line options
#   $log2printAR:      reference to log2print array with log file text
# 
# Returns:  Nothing, if it returns, everything is valid.
# 
####################################################################
sub run_alimanip_to_number{
    my $narg_expected = 5;
    if(scalar(@_) != $narg_expected) { printf STDERR ("ERROR, run_alimanip() entered with %d != %d input arguments.\n", scalar(@_), $narg_expected); exit(1); } 
    my ($alimanip, $aln_file, $gapthresh, $opt_HR, $log2printAR) = @_;

    my $root = $aln_file; 
    $root =~ s/.+\///;  #remove directory path
    if($root =~ s/\.stk$//)    { ; }
    elsif($root =~ s/\.sto$//) { ; }
    # otherwise we'll just append '.cm' to the full name of the alignment file
    my $num_aln_file = $root . $key_out . ".num.stk";

    my $extra_opts = "";
    if(!($opt_HR->{"--rf"})) { # if --rf enabled, we don't redefine consensus columns
	$extra_opts .= " -g --gapthresh $gapthresh";
    }

    if(($opt_HR->{"--num-rf"}) && ($opt_HR->{"--num-all"})) { 
	$extra_opts .= " --num-rf --num-all"; 
	push(@{$log2printAR}, sprintf("#\n# Defining and numbering consensus columns and all columns in alignment file...\n"));
	printf($log2printAR->[(scalar(@{$log2printAR})-1)]);
    }
    elsif($opt_HR->{"--num-rf"})  { 
	$extra_opts .= " --num-rf"; 
	push(@{$log2printAR}, sprintf("#\n# Defining and numbering consensus columns in alignment file...\n"));
	printf($log2printAR->[(scalar(@{$log2printAR})-1)]);
    }
    elsif($opt_HR->{"--num-all"}) { 
	$extra_opts .= " --num-all"; 
	push(@{$log2printAR}, sprintf("#\n# Defining consensus columns and numbering columns in alignment file...\n"));
	printf($log2printAR->[(scalar(@{$log2printAR})-1)]);
    }
    push(@{$log2printAR}, sprintf("#\n"));
    printf($log2printAR->[(scalar(@{$log2printAR})-1)]);
    
    my $command = "$alimanip $extra_opts -o $num_aln_file $aln_file 2>&1";
    my $tmp = `$command`;
    printf("$command\n");
    if(($? >> 8) != 0) { 
	printf STDERR ("\nERROR, the command \(\"$command\"\) unexpectedly returned non-zero exit status %d\nand output:\n$tmp\n", ($? >> 8)); exit($? >> 8); 
    }

    my $max_width = length($num_aln_file);
    if($max_width < length("output aln file")) { $max_width = length("output aln file"); }; 
    my $i;
    my $dashes = ""; for($i = 0; $i < $max_width; $i++) { $dashes .= "-"; }

    push(@{$log2printAR}, sprintf("# %-*s\n", $max_width, "output aln file"));
    printf($log2printAR->[(scalar(@{$log2printAR})-1)]);
    push(@{$log2printAR}, sprintf("# %-*s\n", $max_width, $dashes));
    printf($log2printAR->[(scalar(@{$log2printAR})-1)]);
    push(@{$log2printAR}, sprintf("  %-*s\n", $max_width, $num_aln_file));
    printf($log2printAR->[(scalar(@{$log2printAR})-1)]);

    return;
}


#####################################################################
# subroutine: run_alimanip_to_truncate()
# incept:     EPN, Fri Oct 16 16:20:17 2009
# 
# Purpose:    Run esl-alimanip/ssu-esl-alimanip on an alignment file 
#             to remove leading and trailing columns of the alignment
#             as specified by range <x>..<y> for alignment columns 
#             (with --start-all <x> --end-all <y>) or for consensus
#             columns (with --start-rf <x> --end-rf <y>).
#
# Arguments:  
#   $alimanip:         path and name of esl-alimanip/ssu-esl-alimanip executable
#   $aln_file:         path and name of alignment file to build CM from
#   $gapthresh:        gap threshold to use when building the model
#   $opt_HR:           reference to the hash of command-line options
#   $log2printAR:      reference to log2print array with log file text
# 
# Returns:  Nothing, if it returns, everything is valid.
# 
####################################################################
sub run_alimanip_to_truncate{
    my $narg_expected = 5;
    if(scalar(@_) != $narg_expected) { printf STDERR ("ERROR, run_alimanip() entered with %d != %d input arguments.\n", scalar(@_), $narg_expected); exit(1); } 
    my ($alimanip, $aln_file, $opt_HR, $log2printAR) = @_;

    my $root = $aln_file; 
    $root =~ s/.+\///;  #remove directory path
    if($root =~ s/\.stk$//)    { ; }
    elsif($root =~ s/\.sto$//) { ; }
    # otherwise we'll just append '.cm' to the full name of the alignment file
    my $trunc_aln_file = $root . $key_out;

    if(($opt_HR->{"--start-rf"} ne "") && ($opt_HR->{"--end-rf"} ne "")) {
	$extra_opts .= " --start-rf " . $opt_HR->{"--start-rf"} . " --end-rf " . $opt_HR->{"--end-rf"};
	push(@{$log2printAR}, sprintf("#\n# Truncating alignment; saving columns between consensus columns " . $opt_HR->{"--start-rf"} . " and " . $opt_HR->{"--end-rf"} . "...\n"));
	printf($log2printAR->[(scalar(@{$log2printAR})-1)]);
	$trunc_aln_file .= "rf." . $opt_HR->{"--start-rf"} . "-" . $opt_HR->{"--end-rf"} . ".stk";
    }
    elsif(($opt_HR->{"--start-all"} ne "") && ($opt_HR->{"--end-all"} ne "")) {
	$extra_opts .= " --start-all " . $opt_HR->{"--start-all"} . " --end-all " . $opt_HR->{"--end-all"};
	push(@{$log2printAR}, sprintf("#\n# Truncating alignment; saving columns between columns " . $opt_HR->{"--start-all"} . " and " . $opt_HR->{"--end-all"} . "...\n"));
	printf($log2printAR->[(scalar(@{$log2printAR})-1)]);
	$trunc_aln_file .= "all." . $opt_HR->{"--start-all"} . "-" . $opt_HR->{"--end-all"} . ".stk";
    }
    push(@{$log2printAR}, sprintf("#\n"));
    printf($log2printAR->[(scalar(@{$log2printAR})-1)]);
    
    my $command = "$alimanip $extra_opts -o $trunc_aln_file $aln_file 2>&1";
    my $tmp = `$command`;
    printf("$command\n");
    if(($? >> 8) != 0) { 
	printf STDERR ("\nERROR, the command \(\"$command\"\) unexpectedly returned non-zero exit status %d\nand output:\n$tmp\n", ($? >> 8)); exit($? >> 8); 
    }

    my $max_width = length($trunc_aln_file);
    if($max_width < length("output aln file")) { $max_width = length("output aln file"); }; 
    my $i;
    my $dashes = ""; for($i = 0; $i < $max_width; $i++) { $dashes .= "-"; }

    push(@{$log2printAR}, sprintf("# %-*s\n", $max_width, "output aln file"));
    printf($log2printAR->[(scalar(@{$log2printAR})-1)]);
    push(@{$log2printAR}, sprintf("# %-*s\n", $max_width, $dashes));
    printf($log2printAR->[(scalar(@{$log2printAR})-1)]);
    push(@{$log2printAR}, sprintf("  %-*s\n", $max_width, $trunc_aln_file));
    printf($log2printAR->[(scalar(@{$log2printAR})-1)]);

    return;
}

#####################################################################
# Subroutine: run_ssdraw
# Incept:     EPN, Tue Oct 13 07:15:09 2009
# 
# Purpose:    Call esl-ssdraw for a given alignment and template file.
#             Convert the postscript to pdf if --ps2pdf is enabled.
#
# Arguments:
#   $ssdraw:              path and name of esl-alimanip/ssu-esl-alimanip executable
#   $template_file:       name of template file to use
#   $ssdraw_opts:         string defining options for esl-ssdraw call
#   $aln_file:            alignment file to draw
#   $root:                root for naming output files (with dir)
#   $root2print:          root for naming output files (without dir unless -a, then with dir)
#   $key_out:             optional extra key for output files
#   $draw_key:            another optional extra key for output files
#   $max_width:           width of output string for printing output file names
#   $opt_HR:              REFERENCE to hash of command-line options
#   $n0:                  number of 0s in the mask (passed in)
#   $n1:                  number of 1s in the mask (passed in)
#   $do_column_breakdown: TRUE to print number of columns included vs excluded in output
#   $log2printAR:         reference to log2print array with log file text
#
# Returns:    '1' if esl-ssdraw worked (exited cleanly (returned 0)), 
#             '0' if it did not work (returned non-0 value)
# 
####################################################################
sub run_ssdraw { 
    my $narg_expected = 14;
    if(scalar(@_) != $narg_expected) { printf STDERR ("ERROR, run_ssdraw() entered with %d != %d input arguments.\n", scalar(@_), $narg_expected); exit(1); } 
    my ($ssdraw, $template_file, $ssdraw_opts, $aln_file, $root, $root2print, $key_out, 
	$draw_key, $max_width, $opt_HR, $n0, $n1, $do_column_breakdown, $log2printAR) = @_;

    my($draw_ps, $draw_pdf, $draw_ps2print, $draw_pdf2print);
    $draw_ps         = $root . $key_out . $draw_key . ".ps";
    $draw_pdf        = $root . $key_out . $draw_key . ".pdf";
    $draw_ps2print   = $root2print . $key_out . $draw_key . ".ps";
    $draw_pdf2print  = $root2print . $key_out . $draw_key . ".pdf";

    my $command = "$ssdraw $ssdraw_opts $aln_file $template_file $draw_ps 2>&1";
    #printf("run_ssdraw command: $command\n");
    my $tmp = `$command`;
    if(($? >> 8) != 0) { # it didn't work, don't exit just alert caller by returning 0
	return 0; 
    } 
    
    if($opt_HR->{"--ps2pdf"}) { 
	$command = "ps2pdf $draw_ps $draw_pdf";
	$tmp = `$command`;
	if(($? >> 8) != 0) { printf STDERR ("\nERROR, the command \(\"$command\"\) unexpectedly returned non-zero exit status %d\nand output:\n$tmp\n", ($? >> 8)); exit($? >> 8); } 
	if($do_column_breakdown) { 
	    push(@{$log2printAR}, sprintf("  %-*s  %6s  %4s  %5s  %5s  %5s\n", $max_width, $draw_pdf2print, "output", "pdf", ($n0+$n1), $n1, $n0));
	}
	else { 
	    push(@{$log2printAR}, sprintf("  %-*s  %6s  %4s  %5s  %5s  %5s\n", $max_width, $draw_pdf2print, "output", "pdf", ($n0+$n1), "-", "-"));
	}
	printf($log2printAR->[(scalar(@log2printA)-1)]);

	if(!($opt_HR->{"--ps-keep"})) { 
	    $command = "rm $draw_ps";
	    $tmp = `$command`;
	    if(($? >> 8) != 0) { printf STDERR ("\nERROR, the command \(\"$command\"\) unexpectedly returned non-zero exit status %d\nand output:\n$tmp\n", ($? >> 8)); exit($? >> 8); } 
	}
    }
    # if we didn't do ps2pdf, or if --ps-keep is enabled
    if(!($opt_HR->{"--ps2pdf"}) || ($opt_HR->{"--ps-keep"})) {
	if($do_column_breakdown) { 
	    push(@{$log2printAR}, sprintf("  %-*s  %6s  %4s  %5s  %5s  %5s\n", $max_width, $draw_ps2print, "output", "ps", ($n0+$n1), $n1, $n0));
	}
	else { 
	    push(@{$log2printAR}, sprintf("  %-*s  %6s  %4s  %5s  %5s  %5s\n", $max_width, $draw_ps2print, "output", "ps", ($n0+$n1), "-", "-"));
	}
	printf($log2printAR->[(scalar(@{$log2printAR})-1)]);
    }
    return 1; #if ssdraw failed we returned 0 above
}
